import matplotlib.pyplot as plt
# Pie chart
labels = ['< 10', '10 - 15', '16 - 20']
sizes = [1, 14, 8]
#colors
colors = ['#ff9999','#66b3ff','#99ff99']
#explsion
explode = (0.05,0.05,0.05)

fig1, ax1 = plt.subplots()
 
plt.pie(sizes, colors = colors, labels=labels, autopct='%1.1f%%', startangle=90, pctdistance= 0.7, explode = explode)
# pctdistance = The ratio between the center of each pie slice and the start of the text generated by autopct
1
#draw circle
centre_circle = plt.Circle((0,0),0.70,fc='white')
fig = plt.gcf()
fig.gca().add_artist(centre_circle)

# Equal aspect ratio ensures that pie is drawn as a circle
ax1.axis('equal')  
plt.tight_layout()
plt.show()
